version: '3.8'

services:
  streamer-card:
    build: .
    container_name: streamer-card
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    mem_limit: 1.5g
    cpus: 1.5
    shm_size: 256m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
