services:
  streamer-card-hp:
    build: .
    container_name: streamer-card-high-performance
    ports:
      - "9200:3003"
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - NODE_OPTIONS=--max-old-space-size=1024
      # 高性能配置优化参数
      - LOW_SPEC_MODE=false
      - MAX_CONCURRENCY=3
      - PROTOCOL_TIMEOUT=45000
      - NAVIGATION_TIMEOUT=90000
      - SCREENSHOT_TIMEOUT=45000
      - IMAGE_SCALE=1.5
      - MAX_RETRIES=2
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1.5'
        reservations:
          memory: 512M
          cpus: '0.5'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    shm_size: 512m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
