version: '3.8'

services:
  streamer-card:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME:-streamer-card-app} # Use IMAGE_NAME from .env or default
    container_name: ${CONTAINER_NAME:-streamer-card-container} # Use CONTAINER_NAME from .env or default
    restart: always
    ports:
      - "9200:3003"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - LOW_SPEC_MODE=${LOW_SPEC_MODE:-true}
      - IMAGE_SCALE=${IMAGE_SCALE:-2}
      - MAX_CONCURRENCY=${MAX_CONCURRENCY:-5}
      - MAX_RETRIES=${MAX_RETRIES:-2}
      - PROTOCOL_TIMEOUT=${PROTOCOL_TIMEOUT:-60000}
      - NAVIGATION_TIMEOUT=${NAVIGATION_TIMEOUT:-120000}
      - SCREENSHOT_TIMEOUT=${SCREENSHOT_TIMEOUT:-60000}
      
    volumes:
      - ./src:/app/src
      - /app/node_modules