version: '3.8'

services:
  streamer-card:
    build: .
    container_name: streamer-card-prod
    ports:
      - "9200:3003"
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    mem_limit: 2g
    cpus: 1.0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - streamer-network

  # 可选：添加 Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: streamer-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - streamer-card
    restart: unless-stopped
    networks:
      - streamer-network

networks:
  streamer-network:
    driver: bridge
