services:
  streamer-card-ultra:
    build: .
    container_name: streamer-card-ultra-performance
    ports:
      - "9200:3003"
    environment:
      - NODE_ENV=production
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - NODE_OPTIONS=--max-old-space-size=2048
      # 超高性能配置优化参数
      - LOW_SPEC_MODE=false
      - MAX_CONCURRENCY=5
      - PROTOCOL_TIMEOUT=30000
      - NAVIGATION_TIMEOUT=60000
      - SCREENSHOT_TIMEOUT=30000
      - IMAGE_SCALE=1.2
      - MAX_RETRIES=1
      # 抑制X11警告
      - XKB_DEFAULT_RULES=base
      - XKB_DEFAULT_MODEL=pc105
      - XKB_DEFAULT_LAYOUT=us
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3003/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    shm_size: 1g
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      # 使用tmpfs提高性能
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 512M
